server:
  port: 8080

database:
  host: 'localhost'
  port: 5432
  database: 'rvsjs'
  username: 'rvsjs'
  password: 'rvsjs'
  logging: true

security:
  jwtSecret: 'dev_secret_value'
  jwtExpiresIn: 3600
